name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust 1.88.0
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: "1.88.0"
    
    - name: Install NASM
      run: |
        choco install nasm
        nasm -v
    
    - name: Build project
      run: cargo build --verbose

  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust 1.88.0
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: "1.88.0"
    
    - name: Install NASM
      run: |
        choco install nasm
        nasm -v
    
    - name: Run tests
      run: cargo test --verbose

  run-and-execute:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust 1.88.0
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: "1.88.0"
    
    - name: Install NASM
      run: |
        choco install nasm
        nasm -v
    
    - name: Install GCC (MinGW)
      run: |
        choco install mingw
        gcc --version
    
    - name: Run compiler to generate ASM
      run: cargo run
    
    - name: Compile ASM to object file
      run: nasm -f win64 output.asm -o output.obj
    
    - name: Link and create executable
      run: gcc -o output.exe output.obj -lmsvcrt
    
    - name: Execute the binary
      run: .\output.exe
